version: 2

models:
  - name: stg_mql
    columns:
      - name: mql_id
        tests:
          - unique
          - not_null
      - name: origin
        tests:
          - not_null

  - name: stg_closed_deals
    columns:
      - name: mql_id
        tests:
          - unique
          - not_null